### ISSUE TITLE
Tabbed Scrolling Visual Design

### ISSUE THREAD

**Issue by benarent** [gravitational/next#101]
When visiting the docs on Mac / Chrome, we end out with multiple sidebars. We could hide one with `overflow-y: hidden; ` but the bottom still looks strange.

![image](https://user-images.githubusercontent.com/559288/107717911-8d303c00-6c89-11eb-9de0-469840c45cbb.png)

We could either shorten content or create a visual design / CSS that fixes this issue.

**Comment by klizhentas** [comment]
Yes, we should cap the tab text that overflows the max width

**Comment by iAdramelk** [comment]
@klizhentas we also need to decide what to do with them on mobile. Following situations are possible right now that cause scroll to appear:

- We have few tabs, but the text in them are long – we can fix it with max-width to tab to some degree.
- We have a lot of tabs with short text - we will still not have enough space for them even with max-width for tab.
- We have mobile, there it is usually onle enough space for 1-2 tabs on screen and we still need either scroll or some other design.

**Comment by klizhentas** [comment]
@iAdramelk Alex solved this problem, see the tab switcher with dropdown:

https://app.avocode.com/revisions/78182145/?design=52101148

Let's implement this control instead when working on tabs

**Comment by klizhentas** [comment]
closed in favor of #102
