### ISSUE TITLE
Implement dropdown with tab switcher

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#102]
<img width="862" alt="Screen Shot 2021-02-11 at 8 49 45 PM" src="https://user-images.githubusercontent.com/13717/107731442-d775e500-6caa-11eb-9f5f-5d39ab5eb0fc.png">

See spec here:

https://app.avocode.com/revisions/78182145/?design=52101148

**Comment by Alqanar** [comment]
Created a task https://app.asana.com/0/1201950389251748/1202072765206306
