### ISSUE TITLE
Side-bar nav doesn't remember/highlight selected 3rd level entry

### ISSUE THREAD

**Issue by r0mant** [gravitational/next#110]
Noticed weird behavior with 3rd level side-bar entries. There are a couple of issues:

* When you click on the 3rd level entry, the section collapses and you have to re-open it.
* Some entries are highlighted as active when selected, some are not.

The screencast below shows the issue(-s):

https://user-images.githubusercontent.com/339322/108578702-50db8c00-72d8-11eb-9ece-085bb17ac3b7.mov

**Comment by iAdramelk** [comment]
Fixed
