### ISSUE TITLE
Javascript functions not loading on Docs webpage

### ISSUE THREAD

**Issue by yjperez** [gravitational/next#113]
On the [docs webpage](https://goteleport.com/teleport/docs/production/) unable to use the search function or open any tabs on the side menu. Observing these errors in the console:

```
Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR 

https://goteleport.com/teleport/docs/_next/static/chunks/a9b9bcda1103fbc8d1fc89a1a46edc548c1b03fb.0befbe0d30a4d6a8a44a.js net::ERR_HTTP2_PROTOCOL_ERROR 200
```

OS: MacOS Big Sur v11.2.1
Browsers: Chrome v88.0.4324.192 and Safari v14.0.3
I have cleared the cache and rebooted my machine.

**Comment by benarent** [comment]
I had the same issue, but it's now resolved. 🤷  and without a restart or clearing of cache.

**Comment by yjperez** [comment]
I am also resolved now.

**Comment by klizhentas** [comment]
OK, if it was resolved, then closing

**Comment by wadells** [comment]
Upon further look at the nginx access logs, I see some responses for this particular resource with a shorter length:

The usual response looks like:
```
snip - - [snip] "GET /teleport/docs/_next/static/chunks/a9b9bcda1103fbc8d1fc89a1a46edc548c1b03fb.0befbe0d30a4d6a8a44a.js HTTP/1.1" 200 109495
```

However some have shorter/other lengths:

```
    983 109495
     65 77943
     43 109779
     26 122635
     24 129935
      5 199829
      3 90515
      1 148915
      1 138451
      1 129691
      1 128475
      1 127583
      1 125555
      1 122267
      1 121459
      1 119715
```

We use nginx reverse proxy (`proxy_pass`) for these new docs... perhaps something is up with it:

https://serverfault.com/questions/315085/nginx-proxy-pass-response-truncated

Investigating now.

**Comment by wadells** [comment]
RCA:

[nginx-1.16.1-3.el7.x86_64](https://centos.pkgs.org/7/epel-x86_64/nginx-1.16.1-3.el7.x86_64.rpm.html ) manages `/var/lib/nginx` which includes the default [proxy_temp_path](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_temp_path) directory needed by proxy_pass.

When I applied our provisioning script earlier today, yum reverted the ownership on `/var/lib/nginx` and `/var/lib/nginx/tmp` restulting in errors like:

```
open() "/var/lib/nginx/tmp/proxy/6/91/0000001916" failed (13: Permission denied) while reading upstream
```

When the upstream teleport returned a response large enough for nginx to buffer, it would fail with the above error and return a truncated response to be cached in our CDN, and subsequently distributed to clients.

I'm not sure why this behavior was intermittent yet.

I've temporarily mitigated by adjusting ownership on these directories by hand.  I'll have a PR shortly to make sure they remain fixed.
