### ISSUE TITLE
[Development Request] Teleport Docs URL Change

### ISSUE THREAD

**Issue by yjperez** [gravitational/next#1157]
Please fill out the information below: 

### What is the goal of the ticket? 
The Teleport Documentation page has moved from https://goteleport.com/teleport/docs/ to https://goteleport.com/docs/. This is causing broken links both within some documentation but also within the Teleport product as logs and troubleshooting links point to the old link. Can we have a redirect added until the links are updated?

**Comment by C-STYR** [comment]
Fixed by #1160
