### ISSUE TITLE
Edit links no longer working on docs

### ISSUE THREAD

**Issue by pschisa** [gravitational/next#121]
Clicking the edit links no longer direct the user to a valid Github URL.  It appears they still reference the master branch and not the individual branch for the docs version.

Example from trying to edit Okta SSO on 5.0 and 6.0 versions:
5.0: https://github.com/gravitational/teleport/edit/master/docs/pages/enterprise/sso/ssh-okta.mdx
6.0: https://github.com/gravitational/teleport/edit/master/docs/pages/enterprise/sso/ssh-sso.mdx

**Comment by klizhentas** [comment]
@pschisa great find, we will fix
