### ISSUE TITLE
Do we need this include js snppet?

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#125]
<img width="603" alt="Screen Shot 2021-03-03 at 6 29 35 PM" src="https://user-images.githubusercontent.com/13717/109901777-7492c080-7c4e-11eb-8dd5-03fcfee93309.png">

It's being blocked by Brave browser and I'm not sure we even need it

**Comment by iAdramelk** [comment]
Its [Fathom](https://usefathom.com/)'s script actually. :)
