### ISSUE TITLE
Video failing to load on Jira docs page

### ISSUE THREAD

**Issue by pschisa** [gravitational/next#138]
Imbedded video on Jira docs here: https://goteleport.com/teleport/docs/enterprise/workflow/ssh-approval-jira-server/ does not load successfully.

**Comment by iAdramelk** [comment]
Was an error in the video path. Fixed in:

- https://github.com/gravitational/teleport/pull/5953
- https://github.com/gravitational/teleport/pull/5954
- https://github.com/gravitational/teleport/pull/5955
