### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#142]
Reporting a broken link on the following page: https://goteleport.com/docs/architecture/users/
Broken link: https://goteleport.com/enterprise/introduction/  Show a 404

![image](https://user-images.githubusercontent.com/407237/111529982-05be6880-8720-11eb-8b4b-424f0346c579.png)

**Comment by iAdramelk** [comment]
@klizhentas can you please check. Not sure what should be correct url here.

**Comment by iAdramelk** [comment]
Fixed in current version
