### ISSUE TITLE
Docs do not show the latest version by default

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/next#152]
When navigating to the docs page, it does not show the latest version by default.
When selecting the latest version, it shows this:

![image](https://user-images.githubusercontent.com/7816406/112519856-26666e00-8d71-11eb-9999-0b2767c89d90.png)

**Comment by klizhentas** [comment]
@alex-kovoy that's a UX problem 6.1 is not out yet, so we should probably name it (alpha). Current version is 6.0
