### ISSUE TITLE
``` showing in code rendering with tabs

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/next#168]
On this page https://github.com/gravitational/teleport/edit/branch/v6.0/docs/pages/installation.mdx ``` renders at the end of the code snippets.  Not sure if it's a spacing issue since other similar pages don't have it.  

![image](https://user-images.githubusercontent.com/60704961/113576622-e3688e00-95ed-11eb-9cd7-f411b3c0919c.png)

**Comment by iAdramelk** [comment]
Updating to the new parser from this PR should fix it https://github.com/gravitational/next/pull/161

Will retest later today after we merge it to master.

**Comment by iAdramelk** [comment]
Fixed
