### ISSUE TITLE
Search Issues

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/next#210]
The search feature seems out of synch with the docs content. Users are also taken to the introduction page, not the actual content page. 

Here are examples:

1. If the user search `kuberetes auth sign` they get taken to the intro page
![image](https://user-images.githubusercontent.com/60704961/116239188-5cac5a00-a730-11eb-9f1e-90004f905f7e.png)

2. No search results with teleport-kube-agent which is in the Multiple Clusters.
3. Search Database RBAC and you don't get the RBAC page when you select RBAC, you get the intro page.

**Comment by iAdramelk** [comment]
@klizhentas can you give me access to the docsearch account or share docsearch config with me? Looks like we have an error it config somewhere.

**Comment by iAdramelk** [comment]
@klizhentas my current guess that config is filtering pages to index to `/teleport/docs/` subfolder, but we moved docs to `/docs/` and didnt update it. Current search results are also links to `/teleport/docs/` folder and then redirected.

**Comment by klizhentas** [comment]
* [ ] Evaluate typesense
* [ ] Evaluate paid algolia and build index during vercel build step
