### ISSUE TITLE
Missing Images - teleport/server

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/next#214]
Looks like the static assets (images) at the bottom of https://goteleport.com/teleport/server/#features aren't loading.

Navigate to https://goteleport.com/teleport/server/#features using Brave or Safari:

![Screen Shot 2021-04-27 at 9 53 57 PM](https://user-images.githubusercontent.com/82530006/116339662-720e9c00-a7a3-11eb-8b65-a2199e87fb02.png)

**Comment by iAdramelk** [comment]
@inertial-frame this on is probably for the different repo. These pages are still run on the old hugo site engine that is stored in different repo.

CC @klizhentas where should we fire this one?

**Comment by inertial-frame** [comment]
@iAdramelk - my apologies - will happily resubmit this to the appropriate repo. Thanks!
