### ISSUE TITLE
Block FLOC on Docs and Website engine

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#217]
https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/

why:

https://blog.runcloud.io/google-floc/#what-is-google-floc-why-it-matters

**Comment by iAdramelk** [comment]
@Saionaro can you check this one? It should be easy to add.

**Comment by Saionaro** [comment]
Yep, ready
