### ISSUE TITLE
Design narrow play band

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#222]
We want to create a youtube component that is a narrow "play" band that we can use on top of the page. The current version takes too much space.

@alexwolfe will provide the design and then we'll need a react component.

**Comment by alexwolfe** [comment]
avocode link: https://app.avocode.com/view/109b3ddb4d6a4f52a92933d3a4cbbd9a/_/inspect

![image](https://user-images.githubusercontent.com/407237/116757147-61883c80-a9c2-11eb-9e19-753e37a16e99.png)
