### ISSUE TITLE
Pricing plan post 300+ should switch to enterprise

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#224]
## Description

I've tested on old pricing and new pricing page, so this is not next-related. 

If you move the slider to 300+, the pricing should switch to Enterprise, right now it maxes out on Pro, making an impression that 300+ is not possible.

I think same applies to other resources.

**Comment by twakes** [comment]
I believe the intent was to make the upper bound of each slider the resource count that equals $2,000, since that is the trigger for switching to enterprise.  If that is still the case, we should make the upper bound on the server nodes 400, since each node is $5.

**Comment by alexwolfe** [comment]
Taylor is correct with this. The trigger is generally the price of above $2,000 (unless you choose support or onprem options). Should we update the max limit for these @klizhentas ?

**Comment by alexwolfe** [comment]
@klizhentas @twakes Just following up here.
