### ISSUE TITLE
Signup Landing Page

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#226]
### Signup Page Updates based on preview. 
- [x] Form container should be 488px wide (in can shrink if the window is too small) 
- [x] Video should be 640px wide (also can shrink if window is too small) 
- [x] Title should be (40px font size, 60px line-height, font-weight 600) 
- [x] Sub title should be "Access Plane" not "Plan" 
- [x] Logo should maintain the same position as the left most content on the page and not have a line underneath it. It should also be 40px tall (too small currently) 
- [x] icons should be 32px height/width max 
- [x] Features title should be 16px font size, 24px line-height, bold. Text below is the same except its not bold. 
- [x] Color for features titles and paragraph text should be #455A64
- [x] Background for logo container should be #F6F8F9 
- [x] Title for logo container should be 18px, bold, and  #455A64
- [x] Quotes should look exactly like the quote box on this page: https://goteleport.com/case-study/ the template has a dated design. 

Please create this page using the forms for Cloud and Enterprise: 
- Cloud form: https://goteleport.com/signup/
- Enterprise form: https://goteleport.com/signup/enterprise

The page should be able to play an embedded video. Will will provide you a link to the final URL for this video but please use a place holder for now. 

Avocode version: https://app.avocode.com/view/2884eb5fc44641139e3e6105ace00b62/_/inspect

![image](https://user-images.githubusercontent.com/407237/116920486-891c1680-ac07-11eb-81f7-a7c686b7b576.png)

**Comment by rlutsky** [comment]
Here's what I'm thinking for copy on the Cloud landing page: https://docs.google.com/document/d/1Rg1r8fFhhsCYhlE9g2zpGW9JCibKWNeefQ0SpoWVdSY/edit?usp=sharing

For enterprise we can do the same just switch out the URL, video, form, and remove 'cloud' from the title:
https://docs.google.com/document/d/1s5Uj5ISMDJo6JizHgHJC6NwRvzrWodJtYXyLZbLt4F0/edit?usp=sharing

**Comment by anadeliafadeev** [comment]
@Saionaro same video for both for now, we'll have a fresh demo coming in a few weeks so we'll replace it

**Comment by Saionaro** [comment]
@alexwolfe I reused exact the same components for features and clients lists as careers/about pages uses. Should we really cast variations here?
