### ISSUE TITLE
Broken Images and Links in Docs

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#228]
Our site score for SEO (search engine optimization) has decreased due to the following errors in docs. We need to fix these errors in order to get the score up. Let me know if you have any questions. 

### Pages with broken images
- https://goteleport.com/docs/enterprise/sso/ssh-one-login/  image: https://goteleport.com/img/sso/onelogin/teleport.png
- https://goteleport.com/docs/enterprise/sso/ssh-one-login/ image: https://goteleport.com/img/sso/onelogin/teleportlogo@2x.png
- https://goteleport.com/docs/enterprise/workflow/ssh-approval-mattermost/ image: https://goteleport.com/img/enterprise/plugins/teleport_bot@2x.png
- https://goteleport.com/docs/enterprise/workflow/ssh-approval-slack/ image: https://goteleport.com/img/enterprise/plugins/teleport_bot@2x.png

### Pages with Titles that are too long (70 characters is the max) 
- https://goteleport.com/docs/architecture/authentication/ change to: Teleport Authentication, SSH & Kubernetes certificates | Teleport Docs
- https://goteleport.com/docs/features/ssh-pam/ change to: Configuring Teleport SSH with PAM | Teleport Docs

**Comment by inertial-frame** [comment]
@alexwolfe - Thanks for bringing this to my attention. I'll investigate this more closely and see which versions are impacted. 

@iAdramelk - do you think a lint check for titles would be helpful? Google truncates titles >= 70 so we should flag that.

I think we should also append `| Teleport Docs` automatically going forward (provided the overall title length is lte 70.

**Comment by inertial-frame** [comment]
FYI - looks like it's supposed to be:

```
- [Square Icon](../../../img/sso/onelogin/teleport.png)
- [Rectangular Icon](../../../img/sso/onelogin/teleportlogo@2x.png)
```

Two images with a bullet point. It gets transpiled into `a` elements:

```html
<ul>
    <li>
        <a color="note" class="Link__BaseLink-ad07wf-0 NObiv Link___StyledBaseLink-sc-42coav-0 hkqxpa" href="/docs/ver/img/sso/onelogin/teleport.png">Square Icon</a>
    </li>
    <li>
        <a color="note" class="Link__BaseLink-ad07wf-0 NObiv Link___StyledBaseLink-sc-42coav-0 hkqxpa" href="/docs/ver/img/sso/onelogin/teleportlogo@2x.png">Rectangular Icon</a>
    </li>
</ul>
```

In the process of doing so, the supplied `href` looks like it misaligns from other pics on the page which get something like:

https://goteleport.com/_next/image/?url=%2Fstatic%2Fassets%2Fonelogin-saml-1a-7f3f9ec041.png&w=3840&q=75

So, two issues there. Probably should either recommend not using images in bullet points or should make images render correctly within them. And, looks like the first part of the paths aren't the same?

---

As an immediate documentation fix, I will convert these to images (probably using the new `Figure` component) tonight! That should, I think, make those render correctly.

**Comment by iAdramelk** [comment]
Sorry for the late reaction, I'm on holidays until 17th, and not always near the computer.

@inertial-frame it was my bug actually. See #229 for details.

Basically what was happening here:

`img`folder is not available publicly. So to make files visible we need to move them to folder `/public/`. To do so we use plugin called `remark-copy-linked-files`. It checks asset paths and if it can find this files it moves it to his folder and renames it.

Buuut we also have local links like `[link](../path.mdx)` that should be transformed to `[link](../path/)` to work on actual site. And we can't just remove path form the filename, we need to also modify number of `../`  parts if the path depending the filename (basically leave as is for `index.mdx` page and add `../` for `path,mdx`). All this is done by `utils/remark-links` plugin.

This plugin should have been updating paths only to the page links and ignore images, but I broke it. So what was happening instead:

- `remark-links` was adding `../` to every image link.
- `remark-copy-linked-files` was trying to find image at this new path, but wasn't been able to so it left original urls without modifying it.
- Original URLs were not available publicly, so they resulted in 404s.

**Comment by inertial-frame** [comment]
@iAdramelk - No worries! To be a bit clearer, those Docs could have used an alternative way to display or make available those icons. So, from a Markdown point of view, I'm happy to make any changes to a better or recommended way of doing that (regardless of independent image link or path). We should have validated those paths and used an alternative approach (again, independent of a build bug). As I get up to speed and once the 6.2 items are out, I hope to do a more complete pass through all versions 6.1+ to get images, SEO, etc. 

Thanks for the great fix and analysis!

Also, the title length being <= 70 is something we could improve Markdown-wise, you think a linter might be useful here?

**Comment by iAdramelk** [comment]
@inertial-frame yep, it might be useful. I don't think that there exists plugins to do it already, but it is relatively easy to add. I can work on it after I return, or you can try it yourself if you are interested.

What needs to be done:

- Create `remark-*` plugin file inside `utils` folder. Plugin itself should be written like this: https://github.com/remarkjs/remark-lint/blob/main/packages/remark-lint-heading-increment/index.js#L48 basically wrap function in `rule`. Then write to `file.message` with error text, and corresponding node if something is wrong.
- Add it to this list to build `*.ts` file on server https://github.com/gravitational/next/blob/main/tsconfig.node.json#L14-L19 .
- Add plugin to this list https://github.com/gravitational/next/blob/main/.remarkrc.js#L24-L25 AFTER `frontmatter`. See two selected lines for example of custom linting rules inclusion.

Plugin itself should work like this:

- Check if the first node is `yaml` and parse it. See example of yaml parsing in another plugin https://github.com/gravitational/next/blob/main/utils/remark-import-frontmatter.ts#L26-L31
- Check parsed node content for `title` field and if it is longer than 70 symbols.
- Write error to `file.message` if it is. See linter rule example above for details.
