### ISSUE TITLE
Newsletter stand alone subscribe page

### ISSUE THREAD

**Issue by annabambi** [gravitational/next#262]
We have a design for a newsletter stand-along subscribe page that needs to be built. This is in addition to the newsletter form being available on the footer and in other places.

Link to the avacode web: https://app.avocode.com/view/c454cd60deea4d1ba55dd82d498c1d2a/80612267/inspect/
Link to the avacode mobile (I used iPhone X as an example): https://app.avocode.com/revisions/81083562/?design=54634754

Attaching assets below: 
[subscribe_newsletter_assets.zip](https://github.com/gravitational/next/files/6524613/subscribe_newsletter_assets.zip)
Pin me if you need any other dimensions of the assets.

**I will provide you with the actual text on Monday, there are just text holders for now.**

Please, let me know if you have any questions! Thank you! 🚀

**Comment by rlutsky** [comment]
New copy for the page: https://docs.google.com/document/d/1B30GcyAGImn6Llq9bQegNAPrp2ifAEjTp5NdPE0kIv0/edit?urp=gmail_link
