### ISSUE TITLE
Code snippet component

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#275]
Consider code snippet component:

```
<Code syntax="go">
   <Command> tctl ls </Command>
   Any command output
</Code>
```

This code snippet should render as:

```
$ tctl ls 
 Any command output
```

The copy selection behavior should only copy `tctl ls` and add `$` to the command. So copying this will copy only the command. Combine it with #166 and #84

**Comment by inertial-frame** [comment]
Question: is it better to render the code block like we currently do (`bash`, white text on black background) but then render the console output differently?

1. Docker docs don't seem to support the handy copy-paste functionality ours do but I really like how they use color to contrast the console outputs from the command text:

<img width="856" alt="Screen Shot 2021-05-27 at 6 52 17 PM" src="https://user-images.githubusercontent.com/82530006/119910512-e7919780-bf1c-11eb-8fcc-6d8ddfad891a.png">

2. Kubernetes, on the other hand, puts the output in a follow-up block:

<img width="754" alt="Screen Shot 2021-05-27 at 6 51 44 PM" src="https://user-images.githubusercontent.com/82530006/119910497-dfd1f300-bf1c-11eb-9eb0-b342066386e5.png">

**Comment by inertial-frame** [comment]
3. One last related question: https://github.com/gravitational/next/issues/289 - can we also add support for a child element or prop that would allow a highlighted or bolded placeholder value to be emphasized?
