### ISSUE TITLE
Designed Access Request page

### ISSUE THREAD

**Issue by annabambi** [gravitational/next#297]
Hey @iAdramelk, could you build the Access Request page by following the design and instructions below:

Link to the avocode: https://app.avocode.com/revisions/81310675/?design=54786812

• **Access Plane**: illustration for this section (all files sizes are compressed)
[hero.zip](https://github.com/gravitational/next/files/6587144/hero.zip)

• **Approve Access**: this section is going to have an animation with the terminal and Slack similar to the Home page. Animated GIF is showing the request from the above in Slack, where it gets approved by Alice. We have to show that they are connected. 
Please, contact @alexwolfe when you start working on this, he will also provide you with the text for Lorem Ipsum part. 
Animation as svg: 
[animation.svg.zip](https://github.com/gravitational/next/files/6587154/animation.svg.zip)

• **Core Features**: has similar to the Home Page structure/layout.
For this section, we would like to have an animation of the terminal. The idea is that when you press on any core features, the terminal slides from the right. Depending on the screen size/width, we can adjust the size of the terminal. For wider screens - we show the whole terminal. 
Svg of the terminal with no code: 
[terminal.svg.zip](https://github.com/gravitational/next/files/6587186/terminal.svg.zip)

Move away from roots and admins: Terminal animation, requesting privilege escalation, and supplying a ticket number as a justification for getting a new role. Code:

```
$ tsh request create --roles=dba \   --reviewers=alice@example.com --reason="ticket #124"  

Your request has been sent to Alice
```

Dual Authorization:  @alexwolfe will provide you with the code, which is going to be reflected on the right, shortly.
Customize to fit your needs: code is below: 

```
# use your favorite programming language
def process_request(req):
   #  grant admin only on registered computers
   if req.roles.contains("admin") and registered_computer(req.user):
       raise AccessDenied("use registered computer for privileged access")
   # contractors should provide a valid ticket    
   if req.traits['team'] == "contractor" && not jira.get_ticket(req.note):
      raise AccessDenied("provide an active JIRA ticket")
```

Icons for this section: 
[icons.zip](https://github.com/gravitational/next/files/6587217/icons.zip)

• **Demo section**: the text on the right is going to be a transcript of the video. The length of the transcript will be the same as the height of the video, so we have a nice balanced section (see the design). Link to the demo itself: https://www.youtube.com/watch?v=j8Ze7HhjFGw

• **Quote section**: we made slight adjustments to the design. For the quote itself, you can use current quotes from the website for now.

• **Access Requests Flow**: 
Link: https://goteleport.com/docs/access-controls/guides/dual-authz/
Images: 
[steps.zip](https://github.com/gravitational/next/files/6587274/steps.zip)
Background: 
[background.zip](https://github.com/gravitational/next/files/6587283/background.zip)

Please, contact @alexwolfe if you have any questions!
I will be out until June 15th.
Good luck!!! 🛸

**Comment by kontsevoy** [comment]
My comments by looking at staging:

- Remove "Core features" subtitle. Those things are not "core features"
- Swap the two blocks: "Move away from root accounts" block needs to be on top, with "Works with existing tools" a the bottom.
