### ISSUE TITLE
Make "Improve the Docs" button use a dynamic link to the appropriate .md file

### ISSUE THREAD

**Issue by twakes** [gravitational/next#34]
Ideally, the "Improve the Docs" button would take the user to the .md file for the page they are on. Right now it just dumps the user into the /docs/ repo and then they have to find where to make edits across versions and .md files.

**Comment by twakes** [comment]
It looks like the "edit" button in the top right header already does this, so I'd do the same for the "Improve the Docs" CTA at the bottom.

**Comment by iAdramelk** [comment]
@twakes yep, "Edit" button takes user to the current page, and "Improve the docs" leads to the docs root. I can change it, but want @klizhentas confirmation.

**Comment by klizhentas** [comment]
@iAdramelk I agree with @twakes let's make "Improve the docs" open the current page.
