### ISSUE TITLE
Add team photos to About Us and Careers pages

### ISSUE THREAD

**Issue by annabambi** [gravitational/next#346]
Please, add those photos to About Us and Careers pages. 
Some photos have 500px height and some - 380px (so we have +- an equal number of the photos for each raw).
[new-photos.zip](https://github.com/gravitational/next/files/6773385/new-photos.zip)

Contact me or @alexwolfe for any questions.
Thank you!

**Comment by alexwolfe** [comment]
I've create a PR for this, closing this.
