### ISSUE TITLE
"Share" button in top right header doesn't do anything

### ISSUE THREAD

**Issue by twakes** [gravitational/next#35]

**Comment by iAdramelk** [comment]
We don't have design for it right now, so I for now I just hide it.

**Comment by awly** [comment]
What would it do, other than copy the URL into clipboard?

**Comment by iAdramelk** [comment]
@awly it can, for example, show dropdown with share buttons, that will open socail network specific popup or something else.

**Comment by awly** [comment]
That would make sense for blog posts, but just feels odd for technical docs.

**Comment by awly** [comment]
Are we keeping the "Share" button with social media links or removing it?
