### ISSUE TITLE
Switching to latest does not update the selector

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#36]
1. Click on switch to latest:

<img width="820" alt="Screen Shot 2021-01-15 at 3 11 28 PM" src="https://user-images.githubusercontent.com/13717/104787289-0187c600-5744-11eb-9189-95aa90c2ae17.png">

2. Redirect happens, but the version selector still displays 4.1:
<img width="1073" alt="Screen Shot 2021-01-15 at 3 12 21 PM" src="https://user-images.githubusercontent.com/13717/104787347-1ebc9480-5744-11eb-8f56-f384b70a5a3e.png">

**Comment by iAdramelk** [comment]
Can't reproduce this one. Can you please check the latest version and if the bug persists. Post your browser info.
