### ISSUE TITLE
Feedback on Switcher logic

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#362]
## Description

I've tried the switcher in the docs, here's some changes:

* The URL of the docs should change if I check "Enterprise" in the selector. 
* The UX of "Collapsible" and the naming needs a bit of work

Let's call it `ScopedSection`. The title should contain note that "this content is enterprise". Can this section have labels that are active to illustrate that this content is for OSS, enterprise, or cloud

Same for `ScopedNotice`. Here is a mockup:

![scoped](https://user-images.githubusercontent.com/13717/127374601-8a28795f-626d-4b27-9ee5-8e9f7b6fcb97.jpg)

* We need a special flavor of `ScopedSection flavor=invisible` that hides itself if the scope does not match it as well.

**Comment by klizhentas** [comment]
With new dynamic of releases, there will be faster 2 week release cycle 7.1, 7.2, etc. We need to add element that shows "sub version" of the main version. That this article may be valid only for 7.1 out of 7.0

**Comment by alexwolfe** [comment]
Some notes on the current functionality for the "Type" & "Version" switcher in the docs hero (See image below). 
![image](https://user-images.githubusercontent.com/407237/130487515-dd9c8104-f294-4e9c-9172-82134525e716.png)

The implementation is slightly off which causes unexpected behavior and UX issues. 
1. The version menu should always be present. This does not mean it always has the same options but it should always be available. 
2. When cloud is selected it should always change the URL and show the version of cloud that is selected (which is always the latest stable I believe). None of the other options should be available in the versions dropdown for cloud. This will accomplish a couple things. 
-- First the user will get to the cloud content right away, not having to click an extra link which they may not notice
-- Second it will indicate that cloud is always pegged to the latest version
3. When a user goes from cloud back to enterprise or open source simply select the latest version by default 

Making these changes should solve most of the issues with the type and version switcher. We can make more changes upon testing if neccesary.

**Comment by alexwolfe** [comment]
Here's an updated image for the scoped section component. The labels will indicate the content available and be highlight when a user expands the scoped section. 
![image](https://user-images.githubusercontent.com/407237/130665057-11365a99-32c4-4ed3-8a61-83b55ccd418e.png)

**Comment by klizhentas** [comment]
@alexwolfe can you add a version for "It's available for 7.1+" label?

**Comment by alexwolfe** [comment]
@klizhentas sure

**Comment by alexwolfe** [comment]
updated version: 
![image](https://user-images.githubusercontent.com/407237/130671716-ace19868-b192-4e9a-8b0c-2795427c0f10.png)

**Comment by klizhentas** [comment]
@alexwolfe looks great, thanks

**Comment by iAdramelk** [comment]
@alexwolfe How would it look on mobile? I'm not sure then it will be enough space to place everything in the same line here.

**Comment by alexwolfe** [comment]
@iAdramelk I'll create a design for that too
