### ISSUE TITLE
Add Great Place to Work badge to careers page

### ISSUE THREAD

**Issue by annabambi** [gravitational/next#380]
We were recently certified by Great Place to Work and we want to promote this on our careers page to help with recruiting.

The new section needs to be added above "Our Team All Over the Globe" (https://goteleport.com/careers/).

**Avacode:** https://app.avocode.com/projects/1989192/groups/5985055/
**Folder with all assets:** https://drive.google.com/drive/folders/1kwSloQw1o0Fa6qxNmsj-Yh9MBWb8qQ2t

**Text that we need to use:** 
Our employees make our culture and we strive to make Teleport a desirable place to work by hiring and supporting incredible people. We are extremely proud to have 100% of our employees agree that Teleport is a Great Place to Work.

Please, let me know if you need any help or have any questions!

**Comment by C-STYR** [comment]
Fixed by #384
