### ISSUE TITLE
Redirect users to appropriate pages when changing docs versions.

### ISSUE THREAD

**Issue by sshahcodes** [gravitational/next#382]
### Description
The version selector in docs pages does not maintain links between pages. When a user visits a doc page that is not the current version of Teleport, a warning banner is shown to refer to the latest version. Upon selecting the latest version, the user is redirected to `/docs/` URL which breaks the user flow. 

![docs-page-link](https://user-images.githubusercontent.com/10177602/129189955-102ea157-74a5-4c9d-bf99-066044ef4544.png)

### Solution
1. Maintain a URL map(`old_link : latest_link`) that gets updated in each new Teleport release or docs changes.
2. When user selects the desired version, determine the appropriate URL(from URL map) and pass it to the link and navigation component.

This should be updated in both of the following files:

-  https://github.com/gravitational/next/blob/main/components/DocsPage/DocsPage.tsx

```
               {(isOldVersion || isBetaVersion) && (
                  <Notice mb={4} type="danger">
                    {isOldVersion && (
                      <>
                        This chapter covers a past release: {versions.current}.{" "}
                        We recommend the <Link href="/docs/">latest</Link>{" "}
                        version instead.
                      </>
                    )}
                    {isBetaVersion && (
                      <>
                        This chapter covers an upcoming release:{" "}
                        {versions.current}. We recommend the{" "}
                        <Link href="/docs/">latest</Link> version instead.
                      </>
                    )}
                  </Notice>
                )}
```

- https://github.com/gravitational/next/blob/main/components/DocsPage/Versions.tsx

 ```
 const navigateToVersion = useCallback(
    (version: string) => {
      const isLatest = version === latest;
      const href = `${root}/${isLatest ? "" : `ver/${version}`}`;

      setCurrentItem(version);
      router.push(href);
    },
    [latest, router]
  );
```

**Comment by ptgott** [comment]
@sshahcodes Would there be a way to do this without having to maintain a separate map for all docs pages, which to me sounds difficult to keep up as we add new docs pages? E.g., `Versions` would:
- Only show versions with the same relative path to `/pages`
- Navigate to the page with the same relative path to `/pages` but with a different version

The difficulty here would be that users may still want to navigate to the docs home page for a different version. What do you think, @deliaconstantino @C-STYR @sandylcruz?

**Comment by sshahcodes** [comment]
@ptgott How I missed the notification on this issue! 
I agree that maintaining a separate map can be a challenge. The redirection and version state mantaining solution as implemented in the https://github.com/gravitational/docs/pull/36 PR by @Alqanar looks like a good solution, will cover most of the cases. 

Regarding navigating to home page for a different version, I think it is easier to find and select Home page as compared to finding specific page in the sidebar.
