### ISSUE TITLE
Content is squashed from 500px - 1100px 

### ISSUE THREAD

**Issue by benarent** [gravitational/next#40]
When scrolling mid content, content is pretty squash 

from 500px
![image](https://user-images.githubusercontent.com/559288/104789647-8544b100-574a-11eb-806e-0d3186767598.png)

to 1000px
![image](https://user-images.githubusercontent.com/559288/104789536-3139cc80-574a-11eb-8708-406e27993000.png)

**Comment by iAdramelk** [comment]
Should be fixed in https://github.com/gravitational/next/issues/38
