### ISSUE TITLE
Limit Table of Contents to a defined depth. 

### ISSUE THREAD

**Issue by benarent** [gravitational/next#42]
On https://teleport-docs-next-git-feature-visual-fixes.gravitational.vercel.app/teleport/docs/cli-docs we show multiple headers in the TOC sidebar.  I would suggest we limit to only <h2> tags 

![image](https://user-images.githubusercontent.com/559288/104790142-90e4a780-574b-11eb-856f-6a5054d1cc01.png)

**Comment by klizhentas** [comment]
I agree. TOC should be limited to L2 headers only.

**Comment by alexwolfe** [comment]
Ha was going to leave the same comment

**Comment by awly** [comment]
It's very handy to link to a specific header (at any level), to point customers to docs relevant to their question.
Right now, I can click on a TOC entry and copy the browser URL to do that.
If TOC limits the depth, I can no longer link to specific deeper entries (other than manually crafting the URL).

One neat alternative is having link tags in the content itself, like when you hover over a function name in https://golang.org/pkg/io/
