### ISSUE TITLE
Are docs crawler-friendly?

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#44]
I've tried `wget -m` on the docs and it did not crawl the website. Can you check that crawler can traverse the docs website following anchors

**Comment by iAdramelk** [comment]
@klizhentas we added robots.txt that forbids crawling and from my understanding `wget` is reading it https://www.gnu.org/software/wget/manual/html_node/Robot-Exclusion.html . Should we remove it?

**Comment by klizhentas** [comment]
@iAdramelk let's remove the robots.txt on the day we deploy on prod, so for now all good.
