### ISSUE TITLE
Transfer Tech Papers to new template

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#440]
### Template to use
 https://goteleport.com/downloads/top-10-hacks-of-the-past-decade/

## Pages to Transfer

- [x]  **A Practical Guide to Secure SSH Access**

**Url:** https://goteleport.com/resources/white-papers/practical-guide-to-secure-ssh-access/

**FormID:** 1146

**Copy:** There’s no denying that Secure Shell Protocol (SSH) is the de facto tool for Linux server administration, but is it truly secure? While SSH is widely supported, fairly straightforward to use, and was built with security in mind, it’s far from perfect.
SSH, invented in 1995, is a cryptographic network protocol for accessing UNIX machines securely over an unsecured network. SSH uses a client–server architecture, connecting an SSH client application with an SSH server. It superseded Telnet protocol by adding encryption to prevent malicious actors from eavesdropping on network traffic and compromising data confidentiality and integrity.

**Bullets:** 
- Choosing the right encryption
- Reducing your attack surface with an SSH proxy
- Using industry best practices

**Image:** 
- w:688px h:884 - Will be supplied by Anna 
-------------------------------------------------

- [x]  **Security Best Practices for Privileged Access Management of Cloud-Native Infrastructure**

**Url:** https://goteleport.com/resources/white-papers/security-best-practices-for-pam/

**FormID:** 1139

**Copy:** 
Due to its simplicity and popularity, SSH keys are a popular attack vector for the unauthorized access of server infrastructure, even with the wide availability of key management tooling. In 2014, a Ponemon Institute survey of more than 2,100 systems administrators at Global 2000 companies discovered that three out of four enterprises are vulnerable to root-level attacks against their systems because of their failure to secure SSH keys. These concerns led to the National Institute of Standards and Technology (“NIST”) to publish a 37 page guide on the best practices for securing server access management using SSH. More recently, the increased adoption of elastic, cloud…

**Bullets:** 
- Challenges of Modern Privileged Access Management 
- Security Best Practices Included in Teleport 
- Additional Benefits 

**Image:** 
- w:688px h:884 - Will be supplied by Anna 
-------------------------------------------------

- [x]  **Access and Security Trade-Offs for DevSecOps Teams**

**Url:** https://goteleport.com/resources/white-papers/access-and-security-trade-offs/

**FormID:** 1133

**Copy:** 
Engineering teams building cloud software are always under pressure to deliver new features, fix bugs, and improve performance. To move quickly, engineers need access to computing resources: Kubernetes clusters, individual servers, databases, monitoring dashboards, and so on. But, to a security professional, all of these resources represent an ever-growing attack surface area. Just think how many attack vectors exist in a production database: an attacker can get SSH access to a database machine via a compromised key, a Kubernetes API, a compromised web UI, or even via the database’s own remote protocol.

**Bullets:** 
- Security Overhead
- Common trade-offs
- Emerging Solutions 

**Image:** 
- w:688px h:884 - Will be supplied by Anna 
-------------------------------------------------

- [x]  **The path to Environment-free Computing**

**Url:** https://goteleport.com/resources/white-papers/environment-free-computing/

**FORMID:** Need to be created  

**Copy:** 
Despite advances in software development tooling and the maturing of DevOps, today’s cloud applications and infrastructure are excessively complex and increasingly fragile. Unlike desktop and mobile applications, cloud-native software requires 24⁄7 monitoring and management. This is due largely to the rise of API-driven infrastructure, increased complexity in application architecture, fragmentation of computing environments, and industry reliance on legacy remote management protocols inherited from the client-server era.

**Bullets:** 
- A Brief History of Computing
- The Secure Access Issue in the Cloud Native Era
- The Solution: The Access Plane

**Image:** 
- w:688px h:884 - Will be supplied by Anna 
-------------------------------------------------

- [x]  **Best Practices for Secure Infrastructure Access**

**Url:** https://goteleport.com/resources/white-papers/secure-infrastructure-access/

**FORMID:** 1039

**Copy:** 
As compute resources change dynamically and communicate via public networks, the current implementation of access controls and policy enforcement is becoming an increasingly inexact science. This whitepaper takes a deep look at these trends, the challenges posed by relying on a purely networking-based security policy, and how to reframe this problem in a realistic light. Distilled into key principles used by engineers from small startups to Fortune 5 companies, these four practices provide a strong framework in reconsidering how companies authenticate and authorize users access to critical infrastructure.

**Bullets:** 
- The Current Threat
- Best Practices
- Putting it All Together - Keys vs Certificates

**Image:** 
- w:688px h:884 - Will be supplied by Anna 
-------------------------------------------------

- [x]  **Teleport vs AWS Session Manager**

**Url:** https://goteleport.com/resources/white-papers/teleport-vs-aws-session-manager/

**FORMID:** form needs to be created

**Copy:** 
In this paper, we will provide a brief description of what SSM Session Manager is and how it compares to Teleport privileged access management solution. We’ll compare the significant design and feature differences and the operational overhead of the solutions. Because Session Manager is limited to AWS, we’ll limit the scope of the discussion to that cloud provider. Finally, we have provided a feature matrix of the two solutions.

**Bullets:** 
- How does Session Manager work?
- How does Teleport compare to Session Manager (SM)?
- AWS SSM Run vs tsh ssh

**Image:** 
- w:688px h:884 - Will be supplied by Anna 
-------------------------------------------------

- [x]  **Zero Trust Access Management Best Practices**

**Url:** https://goteleport.com/resources/white-papers/zero-trust-access-management-best-practices/

**FORMID:** 1028 (form has too many fields, needs to be updated) 

**Copy:** 
This guide addresses how to manage access to modern server fleets. Today, organizations are dealing with elastic infrastructure that includes thousands of servers with VMs that are launched and deleted every hour. In addition, the people that need to access the infrastructure may come and go in the organization and their roles may change while they are at the organization. This makes it difficult to implement a scalable system of Zero Trust Access Management to the IT infrastructure.

**Bullets:** 
- AUTHENTICATION AND AUTHORIZATION
- MONITORING AND ALERTING
- SYSTEM ARCHITECTURE AND MAINTENANCE

**Image:** 
- w:688px h:884 - Will be supplied by Anna 
-------------------------------------------------

**Comment by annabambi** [comment]
@alexwolfe @C-STYR 

link to the covers: https://drive.google.com/drive/folders/1EEkjq2ux1x8C01lBWkwjTWmjrHB3zeDr

**Comment by C-STYR** [comment]
@C-STYR 90% complete

**Comment by rlutsky** [comment]
Updated form 1028, and created two additional forms:

- The path to Environment-free Computing: 1175
- Teleport vs AWS Session Manager: 1177
