### ISSUE TITLE
How it works pages

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#450]
The following pages need to be transferred. Please remember to remove the /teleport/ from the URL

### Pages 
- [x] https://goteleport.com/teleport/how-it-works/
- [x] https://goteleport.com/teleport/how-it-works/certificate-based-authentication-ssh-kubernetes/
- [x] https://goteleport.com/teleport/how-it-works/database-access/
- [x] https://goteleport.com/teleport/how-it-works/secure-kubernetes-access/
- [x] https://goteleport.com/teleport/how-it-works/ssh-kubernetes-access-on-the-edge/
- [x] https://goteleport.com/teleport/how-it-works/audit-logging-for-ssh-and-kubernetes/
- [x] https://goteleport.com/teleport/how-it-works/soc2-ssh-kubernetes/
- [x] https://goteleport.com/teleport/how-it-works/fedramp-ssh-kubernetes/
- [x] https://goteleport.com/teleport/how-it-works/hipaa-compliance/

**Comment by C-STYR** [comment]
@C-STYR will be handling this one...
