### ISSUE TITLE
Contact Us Form

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#453]
Current Page: https://goteleport.com/contact-us/

We can use the following design when we reimplement the new contact us page: 
![image](https://user-images.githubusercontent.com/407237/139098459-3b1fd664-1cb7-47b2-b8ad-2f1764e2ed80.png)

**Comment by annabambi** [comment]
@C-STYR 

Link to avacode:
form 1: https://app.avocode.com/revisions/84166747/?design=56531652
form 2: https://app.avocode.com/revisions/84166746/?design=56531651

The difference between the forms is that the first one has first and last names on one line, and the second form - on two different lines. Please, use the one that is easier for you. 

Link to illustration: https://drive.google.com/drive/folders/17NLZnynuV0NVvfu0nAm6gcsnFD1l03vd


Please, use a purple background for this project, as a reference: https://goteleport.com/thanks/
