### ISSUE TITLE
ToC entries are a mix of purple and grey colors

### ISSUE THREAD

**Issue by r0mant** [gravitational/next#472]
I think this started happening just a few days ago but in Chrome our table of content entries have a mix of purple and grey colors:

<img width="232" alt="Screen Shot 2021-10-01 at 11 56 37 AM" src="https://user-images.githubusercontent.com/339322/135672588-9c43fce6-6e08-4406-84f7-fe060b91072e.png">

This seems to only affect Chrome.

**Comment by iAdramelk** [comment]
It's visited links. While adding scopes I reused Link component that we used for the main page body in the menu and that component had visited state. Will remove it.
