### ISSUE TITLE
TOC should make different header levels distinct

### ISSUE THREAD

**Issue by awly** [gravitational/next#49]
Table of contents renders all header levels (h1/h2/h3...) the same way.
It makes it harder to find top-level sections in a long page like the Admin Guide.

![Screenshot_2021-01-19 Teleport Admin Manual](https://user-images.githubusercontent.com/1146263/105084433-2f725080-5a4b-11eb-9e38-8a7f56e0a592.png)

**Comment by klizhentas** [comment]
This is not necessary, because we are going to limit TOC on the right to just one level

https://github.com/gravitational/next/issues/42
