### ISSUE TITLE
Single Sign-On (SSO) for SSH and Kubernetes

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#498]
https://goteleport.com/teleport/features/sso-for-ssh/

**Comment by Alqanar** [comment]
https://teleport-docs-next-git-features-pages-layout-gravitational.vercel.app/features/sso-for-ssh/

@alexwolfe @annabambi
I added a link to preview the page in the new design.
But unfortunately, I have no idea what to write in the Terminal widget (image). In Terminal, the page should have 3 tabs.
It would be great if someone could suggest commands for these tabs.
