### ISSUE TITLE
Role-based access control for SSH and Kubernete

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#500]
https://goteleport.com/teleport/features/rbac-for-ssh/

**Comment by Alqanar** [comment]
https://teleport-docs-next-git-features-pages-layout-gravitational.vercel.app/features/rbac-for-ssh/

@alexwolfe @annabambi 
I added a link to preview the page in the new design.
But unfortunately, I have no idea what to write in the Terminal widget (image). In Terminal, the RBAC page should have 4 tabs. 
It would be great if someone could suggest commands for these tabs.
