### ISSUE TITLE
Build SaaS Vertical Page

### ISSUE THREAD

**Issue by annabambi** [gravitational/next#516]
@alexwolfe will contact you in terms of the layout of the page.
More context you can find here: **ticket** [#2269](https://github.com/gravitational/web/issues/2269)

Link to the assets: https://drive.google.com/drive/folders/1bBmxlA65027H0LOHgkCFFa1QO-zPr6MZ
Use attached to the folder gif for the **"Complete visibility into access and behavior"** section.

I wasn't able to find logos for Orbit and DataLab (not sure which ones are needed specifically).

**Comment by C-STYR** [comment]
closed by #524
