### ISSUE TITLE
Build Internet & Entertainment Vertical Page

### ISSUE THREAD

**Issue by annabambi** [gravitational/next#518]
@alexwolfe will contact you in terms of the layout of the page.
More context you can find here: **ticket**[ #2273 ](https://github.com/gravitational/web/issues/2273)

Link to the assets: https://drive.google.com/drive/folders/1beufsd7bQnh5UyV88zliZiuCk0OMoHyc
Use attached to the folder gif for the **"Designed for digital-native commerce"** section.

**Comment by C-STYR** [comment]
closed by #524
