### ISSUE TITLE
Fix the footer to the bottom of the page

### ISSUE THREAD

**Issue by Alqanar** [gravitational/next#538]
On small pages, our footer follows the previous section. And we have an empty space between the footer and the bottom of the page.

<img width="1661" alt="Screenshot 2021-10-25 at 15 46 28" src="https://user-images.githubusercontent.com/41822696/138697996-b0d74b9d-b13c-4d25-8d3f-1ee28eeeaae6.png">

**Comment by alexwolfe** [comment]
I'm going to close this one. Not much we can do on this unless we create a fixed position footer which I do not want to do. Technically the page has ended which is why you see this gap.
