### ISSUE TITLE
Black background not rendering on items with horizontal scrolls and white text

### ISSUE THREAD

**Issue by pschisa** [gravitational/next#555]
The example underneath https://goteleport.com/docs/setup/guides/terraform-provider/#step-14-install-terraform-provider has a horizontal scroll option to view the full command.  The black background does not cover the entire box, making the text as you scroll over white on white and impossible to read.

Seems like an issue with any white text example.  See https://goteleport.com/docs/kubernetes-access/helm/guides/gcp/#step-5-set-values-to-configure-the-cluster.  The  "Using values.yaml" example has color text and the black background covers the area with the scroll bar.  The same example, different tab "Using --set via CLI" has white text and the black background does not cover the whole scroll bar area.

**Comment by pschisa** [comment]
Issue was noticed when using Chrome and Firefox web browsers

**Comment by iAdramelk** [comment]
@alexwolfe Hey Alex. I made some research on this issue and it will be hard to fix it with current design. We want code block to have horizontal scroll inside it for large code blocks, and to do it we need to add overflow to it. But right now we have `copy code line` icons that are placed outside left end of the code block that will be cut if we use it. Can we update this design in some way?

**Comment by alexwolfe** [comment]
I think this issue could be resolved in the particular case we simply indent the line and show the copy symbol when a user hovers instead of having it pop out of the terminal. This will allow us to have an overflow:auto on the code box so everything shows up correctly
