### ISSUE TITLE
Remove old raffle pages

### ISSUE THREAD

**Issue by sandylcruz** [gravitational/next#556]
The following conventions and raffles have already happened, and their corresponding raffle pages should be deleted as well. Can you confirm that these pages are okay to be removed? @nicobon5 @rlutsky

Raffles to be deleted:
- All Day DevOps (10/28)
- Devopsdays Houston (9/21- 9/22)
- ElasticON
- KubeCon (10/13 - 10/15)
- ShellCon (10/8 - 10/9)
- SREcon (10/12 - 10/14)

**Comment by nicobon5** [comment]
They certainly can be deleted, thank you!
