### ISSUE TITLE
Site wide search

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#558]
We currently have search for documentation but we'd like to implement a search that covers the rest of the site excluding docs. 

The order of searching  might depend on the page. For example, if you are on the blog the search would default to blog articles first, then resources, then the rest of the site. 

If you were on the resources page we might show resources first, then blog articles then the rest of the site. 

I'd like us to investigate if this is possible with Algolia.

**Comment by Alqanar** [comment]
@alexwolfe Yes, it's possible to do with Algolia. As far as I know we already have a paid account there, don't we?
How priority is that task? Can I finish with podcasts pages or should I switch to this task as soon as possible?

**Comment by C-STYR** [comment]
@Alqanar per Alex, please finish with the podcast pages first, thanks!
