### ISSUE TITLE
ThredUp Case Study

### ISSUE THREAD

**Issue by annabambi** [gravitational/next#575]
Build the ThredUp case study page.

**Design:** https://www.figma.com/file/q6VDs2NkDzmxXvivVpSI7o/ThredUP-Case-Study?node-id=0%3A1

**Google Doc:** https://docs.google.com/document/d/1mmG1Wx7EaqBiWIUcwzgui0_SG7L8Caq7vrGetsZArJI/edit#heading=h.6ef1ox49fmb1
(see **Rosalind's notes here**: https://github.com/gravitational/web/issues/2381)

**Assets/images/diagrams:** https://drive.google.com/drive/folders/1TOXESU375ZHaOuIah6gz2i7EggaptBFR
(please, **use the same images** as on the design)

**Icons:** https://drive.google.com/drive/folders/19RaYSzFKpSFdevS7GcFeXEP86gKdzfTW

same as: https://github.com/gravitational/web/issues/2381

**Comment by C-STYR** [comment]
@rlutsky @alexwolfe status update: this page is 98% complete, but there are some bugs in the underlying layout that need to be fixed before it can go live.  I had hoped to have this done today, but it'll probably be Monday or Tuesday next week before I solve the issue.
