### ISSUE TITLE
Migrate mkdocs python plugins to remark

### ISSUE THREAD

**Issue by iAdramelk** [gravitational/next#6]
These plugins are currently used in the mkdocs site:

  - [x] [admonition](https://python-markdown.github.io/extensions/admonition/)
  - [x] [def_list](https://python-markdown.github.io/extensions/definition_lists/)
  - [x] [footnotes](https://python-markdown.github.io/extensions/footnotes/)
  - [x] [pymdownx.tabbed](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/)
  - [x] [pymdownx.superfences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/)

We need to either find `remark` alternatives, or write our own.

**Comment by iAdramelk** [comment]
Plugin status:

**admonition** –  Remark analogue exists, but with slightly different syntax: https://github.com/elviswolcott/remark-admonitions . 

Will try to make our own simplified copy.

**def_list** – I tried searching docs for it, but can't find any cases where it was used. At least not in the `5.0` docs. We probably should try to remove it from the current site and check if anything breaks.

**footnotes** – Remark analogue with the exact syntax exists, but I can't find any cases of its usage in the actual docs. Will leave it enabled for now, but we should also try to remove it from the current site to check differences.

**pymdownx.tabbed** – No direct remark analogue. Docsaurus is using MDX instead: https://v2.docusaurus.io/docs/markdown-features/#tabs

Will try to rewrite it and will report about how hard it is. If it will take too much time we can discuss option of using Docsaurus approach.

**pymdownx.superfences** – It's a plugin to allow some insane nested constructions. Can't say if it is used somewhere now or not because it's hard to search. I suggest we try to disable it on the current site and check how much difference are in results. It will probably be quite hard to replicate in remark because of tons of possible edge cases.

CC @klizhentas

**Comment by klizhentas** [comment]
I have checked and all these plugins are shipped as a bundle https://facelessuser.github.io/pymdown-extensions/
It will take some time to pick plugins that we while turning off the others without this bundle.
Let's take the risk and assume that `superfences`, `def_list` and `footnotes` are not needed.

**Comment by iAdramelk** [comment]
@klizhentas I think you can just disable them there: https://github.com/gravitational/teleport/blob/master/docs/5.0.yaml#L19-L23

I will try to build original docs today and diff build results and report about the differences.

**Comment by iAdramelk** [comment]
@klizhentas ok, I run some tests and results are:

1. `def_list` and `footnotes` are not used anywhere at all. Diff shown zero changes.
2. `toc` plugin is only used in markdown body to add anchors to the headers. We are doing it with another plugin in the new docs, so we can ignore it.
3. `pymdownx.superfences` – this is the strange one. This plugin itself can do million different things, but from that I can see in diffs, it only used to replace old code formatter with the `Pygments`: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#code-highlighting . At least I checked `5.0`'s diff manually and didn't catch any other changes.

So I'd say we can ignore all these plugins for now and only focus on `tabbed` and `admonition`.
