### ISSUE TITLE
Fathom conversion goal trackers for links

### ISSUE THREAD

**Issue by benarent** [gravitational/next#62]
### Motivation:
Deployed Teleport clusters have a help and support section which links to Teleport Docs. When a customer visits one of these links they send along query parameters. Example `https://goteleport.com/teleport/docs/quickstart/?product=teleport&version=e_5.1.0`.

This data is helpful to get a baseline for deployed community and enterprise clusters. It’s possible to infer deployed clusters by looking at referrers, especially if they have `:3080` in the URL. 
 
###  Request:
When a customer visits Teleport documentation with our defined query parameters we’ll anonymously track this event. I would suggest we send the event on page load. Per https://usefathom.com/support/goals 

### Implementation

Make it easy to embed goal trackers in the MDX format, there are two alternative syntax that come to mind:

custom react component:

```
<a href="..." Goal="AUIYDOG4">Pretty Straightforward to use</a>
```

or markdown compatible:

```
[Custom goal](link#GOAL)
```

**Comment by benarent** [comment]
@klizhentas PTAL as a proposal to better track traffic from deployed community and enterprise clusters.

**Comment by klizhentas** [comment]
we will come up with another syntax for this (why not use a href directly with custom attribute?). this is in scope of #24
