### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#64]
Set up redirect:

/teleport/docs/kubernetes-ssh/ -> /teleport/docs/kubernetes-access/

Broken link on this page:

https://gravitational.co/teleport/docs/admin-guide/

https://gravitational.co/teleport/docs/admin-guide/metrics-logs-reference/

On the original docs this link points to a different location:

https://goteleport.com/teleport/docs/metrics-logs-reference/

There are bunch of other broken links here: https://www.semrush.com/siteaudit/campaign/4056093/review/#issue/detail/8

**Comment by iAdramelk** [comment]
@klizhentas I don't have rights to access this semrush report. Can you please check if I'm added to it?

**Comment by iAdramelk** [comment]
- Fixed problem with `/teleport/docs/kubernetes-ssh/` (old redirect in vercel.json only worked with `/teleport/docs/kubernetes-ssh`, now it works with both).
- Added redirect `/teleport/docs/admin-guide/metrics-logs-reference/` -> `/teleport/docs/metrics-logs-reference/`.

**Comment by klizhentas** [comment]
The first link needed a redirect, but the second link was generated wrong:

[metrics reference](metrics-logs-reference.md) is generated as root level link in old docs, but as local links in the new logs

**Comment by klizhentas** [comment]
Example from this section: https://github.com/gravitational/teleport/blob/master/docs/5.0/admin-guide.md#troubleshooting

Can you please remove the second redirect, but not first. And change the logic for local links with no qualifier to be generated differently.

**Comment by iAdramelk** [comment]
Can you please check if this issue is fixed for all necessary link in the current version?
