### ISSUE TITLE
Preview link is undefined

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#67]
<img width="1140" alt="Screen Shot 2021-01-26 at 12 21 02 PM" src="https://user-images.githubusercontent.com/13717/105900508-00228d00-5fd1-11eb-8cf9-6c72d915356f.png">

When there is no root section doc defined, like in this `/preview` can you set up redirect tot he first valid page instead of 404?

**Comment by iAdramelk** [comment]
Added manual 307 (non-permanent) redirects because there is no logic to select correct ones automatically.
