### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#69]
<img width="1124" alt="Screen Shot 2021-01-26 at 12 48 35 PM" src="https://user-images.githubusercontent.com/13717/105903544-d9665580-5fd4-11eb-984e-7ccf13b98a0b.png">

**Comment by klizhentas** [comment]
@iAdramelk the links are broken because of the URL rendered wrong, notice /teleport/docs used twice:

https://gravitational.co/teleport/docs/teleport/docs/assets/teleportlogo@2x-49159aee85.png

**Comment by iAdramelk** [comment]
Should be fixed now.
