### ISSUE TITLE
Add ability to link to and force open a Details section

### ISSUE THREAD

**Issue by programmerq** [gravitational/next#695]
When sharing links to the documentation with teleport users, it may be necessary to point out some content this is in a Details section that is not opened by default.

For example, the "Troubleshooting: failed to create a lock?" Details on https://goteleport.com/docs/access-controls/guides/locking/?scope=enterprise#step-12-create-a-lock is not opened until the user clicks on it.

![image](https://user-images.githubusercontent.com/37278/146586867-835cde58-fcdd-42f7-93c9-676f46314c2d.png)

If I need to share the content of that section with an end user, it would be ideal to have the ability to have an anchor specifically for that location so it will drop the user on that Details section with it already opened. For example: https://goteleport.com/docs/access-controls/guides/locking/?scope=enterprise#troubleshooting-failed-to-create-a-lock would land the user on this view instead:

![image](https://user-images.githubusercontent.com/37278/146586960-870ecb12-2813-4231-9505-7de130729cc6.png)

That way it will be more obvious that I'm directing the user to that specific details section explicitly.

**Comment by Alqanar** [comment]
Created a task https://app.asana.com/0/1201950389251748/1202072765206286/f
