### ISSUE TITLE
Inconsistencies with highlighting/colours in code blocks

### ISSUE THREAD

**Issue by webvictim** [gravitational/next#73]
![Screenshot 2021-01-29 at 15 50 28](https://user-images.githubusercontent.com/897821/106320995-0a02f500-624a-11eb-9035-3c2454071d38.png)

`yes` here is red

![Screenshot 2021-01-29 at 15 50 32](https://user-images.githubusercontent.com/897821/106321103-36b70c80-624a-11eb-9b3b-ccecc8afb2d4.png)

but `"yes"` here is green (also seen the same thing with `true`/`false`)

![Screenshot 2021-01-29 at 15 50 39](https://user-images.githubusercontent.com/897821/106321042-1be49800-624a-11eb-8100-889bb92128ee.png)

`proxy.example.com:3080` is green here but only the `3027` of `0.0.0.0:3027` is

**Comment by klizhentas** [comment]
yes seems to be constant in the first case and string in others, and the yaml below is incorrect, so not sure it's a real bug

**Comment by webvictim** [comment]
This is probably true, but it's a customer-facing issue that wasn't present with our old docs engine.

We should do a pass over at least the latest version of the docs to wrap all values in `"`, standardise on `true` or `"true"` rather than `yes` etc.

**Comment by klizhentas** [comment]
let's postpone this for now, this is just YAML formatting glitches
