### ISSUE TITLE
Search Results

### ISSUE THREAD

**Issue by Virag-Mody** [gravitational/next#77]
Searching a phrase shows matches in real-time, but when pressing enter, it goes directly to the first suggestion.

E.g. If I type in "reverse tunnel" it displays a list of headers that I might want. But clicking enter without choosing one takes me to the first result.

I have a habit of searching and pressing enter to look at an index. I think there's should be a page after blindly clicking enter that shows a (pretty) indexing of results.

**Comment by Virag-Mody** [comment]
@klizhentas I cannot label this (User Test)

**Comment by iAdramelk** [comment]
This can't be implemented with the standard `docsearch.js` that Algolia provides for OSS sites. But we can make custom implementation of this by using Algolias API and implementing UI directly without using `docsearch.js` if we want.

**Comment by Virag-Mody** [comment]
Probably not necessary, this is just a 'nice-to-have'
I'll close the ticket
