### ISSUE TITLE
Rendering issues and broken include

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#78]
<img width="910" alt="Screen Shot 2021-01-29 at 3 17 34 PM" src="https://user-images.githubusercontent.com/13717/106337117-3ff1aa80-6245-11eb-9a92-4adfc8893774.png">

**Comment by iAdramelk** [comment]
@klizhentas There were two separate issues:

- One above was about different import syntax from that I'm added to the new docs. Fixed i here: https://github.com/gravitational/teleport/pull/5446
- But after I fixed it I found additional bug on my side then import was added with unneeded newlines. So I fixed it too and commit to `main` with some tests to prevent having this issue again.
After merging first one to the `teleport` repo we need to manually run build in vercel to deploy it.
