### ISSUE TITLE
Edits for https://goteleport.com/ssh-server-access/

### ISSUE THREAD

**Issue by sageanya** [gravitational/next#784]
@C-STYR 

Suggested edits for **https://goteleport.com/ssh-server-access/**
1. Change "Access Requests" in the third column subhead to: Access requests
2. Under "Access Requests" in the third column, change plug-ins to: plugins
2. Edit subhead "For Compliance-Minded Engineers" to: For compliance-minded engineers
3. Edit subhead "For Developers" to: For developers
4. Under subhead "Live server inventory", delete the comma after "discovery"
5. Edit subhead "For Security Professionals" to: For security professionals
6. Edit subhead "Session Recording" to: Session recording
7. Edit subhead "Kernel level logging" to: Kernel-level logging
8. Under subhead "Works with everything you have", delete "it" in the first sentence and delete "hyphen" from "single-binary" to make it "single binary"
9. If you are following title-case capitalization for button CTA's across the website, then the "Get started" button CTA at the bottom would be: Get Started
10. In the DEMO tile under "Learn more about Teleport Server Access" subhead, edit "Five minute demo of Teleport" to: Five-minute demo of Teleport
11. In the DEMO tile mentioned above (blurb's second line), replace comma after "Teleport" with a period.

**Comment by deliaconstantino** [comment]
close with https://github.com/gravitational/next/pull/794
