### ISSUE TITLE
Edits for https://goteleport.com/kubernetes-access/

### ISSUE THREAD

**Issue by sageanya** [gravitational/next#788]
@C-STYR 

Suggested edits for: **https://goteleport.com/kubernetes-access/**

1. Edit "Access Requests" subhead to: Access requests
2. Under "Access Requests" subhead, change plug-ins to: plugins
3. Edit "Per Session MFA" subhead to: Per-session MFA
4. Edit subhead "For Compliance-Minded Engineers" to: For compliance-minded engineers
5. Edit subhead "For Security Professionals" to: For security professionals
6. Edit subhead "Session Recording" to: Session recording
7. Under subhead "Session Recording", subhead "Live View", and subhead "Teleport Terminal": kubectl would need to be in code font if it's to match the messaging guide.
8. Edit "Live View" subhead to: Live view
9. Under "Live View" subhead: add "and" before "access"
10. Edit "For Developers" to: For developers
11. Under subhead "Secure access that doesn't get in the way", add "and" before "hopping".
12. Edit subhead "Live Cluster Inventory" to: Live cluster inventory
13. Edit subhead "Access as Code" to: Access as code
14. Under subhead "Works with everything you have", delete "it" in the first sentence and delete "hyphen" from "single-binary" to make it "single binary"
15. If you are following title-case capitalization for button CTA's across the website, then the "Get started" button CTA at the bottom would be: Get Started
16. In the DEMO tile under "Learn more about Teleport Kubernetes Access" subhead, edit "Five minute demo of Teleport" to: Five-minute demo of Teleport
17. In the DEMO tile mentioned above (blurb's second line), replace comma after "Teleport" with a period.

**Comment by C-STYR** [comment]
@sageanya thanks! If these (and your other PRs) are ready to go please assign me as a reviewer and I will delegate to the appropriate person.

**Comment by sageanya** [comment]
@C-STYR It doesn't seem I have permission to assign issues to team members, but I tagged you in the three issues so far opened, and will tag you in the upcoming 2 issues.

**Comment by deliaconstantino** [comment]
close with https://github.com/gravitational/next/pull/794
