### ISSUE TITLE
Edits for https://goteleport.com/database-access/

### ISSUE THREAD

**Issue by sageanya** [gravitational/next#790]
@C-STYR 

Suggested edits for **https://goteleport.com/database-access/**:
1. Under subhead "Easily secure your databases using security best practices", add comma after "RBAC".
2. Edit subhead "Access Requests" to: Access requests
3. Under subhead "Access Requests", edit "plug-ins" to: plugins
4. Edit subhead "Consolidated Policy" to: Consolidated policy
5. Edit subhead "For Compliance-Minded Engineers" to: For compliance-minded engineers
6. Under "Session controls" subhead, add comma after "termination"
7. Edit subhead "For Developers" to: For developers
8. Edit subhead "Delightful Experience" to: Delightful experience
9. Edit subhead "Unified Connectivity" to: Unified connectivity
10. Edit subhead "Multi Platform" to: Multi-platform
11. Edit subhead "Audit Log" to: Audit log
12. Under subhead "Live database catalog", add comma after "access"
13. Under subhead "Works with everything you have", delete "it" in the first sentence and delete "hyphen" from "single-binary" to make it "single binary"
14. If you are following title-case capitalization for button CTA's across the website, then the "Get started" button CTA at the bottom would be: Get Started
15. In the DEMO tile under "Learn more about Teleport Database Access" subhead, edit "Five minute demo of Teleport" to: Five-minute demo of Teleport
16. In the DEMO tile mentioned above (blurb's second line), replace comma after "Teleport" with a period.

**Comment by deliaconstantino** [comment]
close with https://github.com/gravitational/next/pull/794
