### ISSUE TITLE
Edits to https://goteleport.com/application-access/

### ISSUE THREAD

**Issue by sageanya** [gravitational/next#791]
@C-STYR 

Suggested edits to: **Edits to https://goteleport.com/application-access/**

1. Edit subhead "Single Sign On with MFA" to: Single sign-on with MFA
2. Under subhead "Single Sign On with MFA", add and before "MFA".
3. Edit "Unified Access Policy" to: Unified access policy
4. Edit "For Compliance-Minded Engineers" to: For compliance-minded engineers
5. Under subhead "Session controls", add comma after "termination"
6. Set the 6 subheads in sentence case, as such: Endpoint management, Access provisioning, Application Launcher, Unified audit log, Unified session management, Live application catalog
7. Edit subhead "For Security Professionals" to: For security professionals
8. Under subhead "Works with everything you have", delete "it" in the first sentence and delete "hyphen" from "single-binary" to make it "single binary"
9. If you are following title-case capitalization for button CTA's across the website, then the "Get started" button CTA at the bottom would be: Get Started
10. Change the subhead that says "Learn more about Teleport Kubernetes Access" to "Learn more about Teleport Application Access" since this page is about Application Access rather than Kubernetes Access.
11. In the DEMO tile under "Learn more about Teleport Application Access" subhead, edit "Five minute demo of Teleport" to: Five-minute demo of Teleport
12. In the DEMO tile mentioned above (blurb's second line), replace comma after "Teleport" with a period.

**Comment by deliaconstantino** [comment]
close with https://github.com/gravitational/next/pull/794
