### ISSUE TITLE
Detect broken external and internal links during deploy

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#80]
## Broken links

* [x] Auto detect broken local links during builds
* [ ] Verify that links are in the sitemap

**Comment by klizhentas** [comment]
@webvictim hey, just to confirm, have we turned the CI/CD part on?

**Comment by webvictim** [comment]
Yes, the Teleport CI part is enabled now - see steps like this: https://drone.gravitational.io/gravitational/teleport/7920/2/3

Although I just noticed that check generated 2 warnings, but for some reason the Drone pipeline still exited with success. @iAdramelk does remark treat warnings differently to errors, or maybe still exit with a zero exit code for warnings?

I also need to backport the changes to other branches as we currently only run the new linter on PRs to `master`.

**Comment by iAdramelk** [comment]
@webvictim  Yes, I think `remark-lint` may not throw on warnings. Will check.

**Comment by webvictim** [comment]
@iAdramelk Did you figure out how we could make `remark-lint` fail on warnings? I've just noticed that we have a lot of warnings in the linter job: https://drone.gravitational.io/gravitational/teleport/9081/2/3

**Comment by iAdramelk** [comment]
@webvictim yes adding `--frail` to [this line](https://github.com/gravitational/next/blob/feature/move-variables-to-mdx/package.json#L22) should do it. I fixed it in other pr that also changes variables syntax, but I didn't yet merged it because I want to first prepare few PRs with fixes and syntax changes to the main docs.

**Comment by webvictim** [comment]
@iAdramelk No problem, thanks. I raised https://github.com/gravitational/teleport/pull/6228 to enable this and fix most of the glitches - not sure if that's duplicating stuff you've already done.

**Comment by iAdramelk** [comment]
Enabled `--frail` in `main` after fixing all error in the latest PR. Closing for now.
