### ISSUE TITLE
Tiles

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#81]
## Tiles 

Implement components for [Home page](https://app.avocode.com/revisions/77798605/?design=51945807) and [Guides](https://app.avocode.com/revisions/77798568/?design=51942921)

**Comment by klizhentas** [comment]
<img width="887" alt="Screen Shot 2021-04-09 at 2 18 13 PM" src="https://user-images.githubusercontent.com/13717/114241733-85fe7500-993e-11eb-92a7-1f5f9ef79842.png">

@iAdramelk see above, our tiles should also support variable width

**Comment by iAdramelk** [comment]
Closing it for now. We can add new types of tiles in separate issue then design is ready.
