### ISSUE TITLE
Escaped newlines in ```code snippets rendering as spaces

### ISSUE THREAD

**Issue by ptgott** [gravitational/next#811]
[For example](https://goteleport.com/docs/kubernetes-access/helm/guides/aws/#step-5-set-values-to-configure-the-cluster):

![image](https://user-images.githubusercontent.com/25250668/150858257-39030a77-874b-4cb1-abd7-ea00623d794a.png)

Since we're moving code snippets toward the `code` format, this means that a lot of commands with flags that span multiple lines (e.g., `helm install` commands) render unexpectedly.

**Comment by C-STYR** [comment]
@ptgott can you please give a more full explanation of what you'd like to see as the desired functionality?

**Comment by ptgott** [comment]
@C-STYR 

For CLI commands that are particularly long due to multiple flags, it's typical to add an escaped newline (`\\n`) at the end of each line so that each flag appears on its own line.

Rather than appear as:

```
$ helm install teleport teleport/teleport-cluster \  --create-namespace \  --namespace teleport \  -f aws-values.yaml
```

The command in the example should appear as:

```
$ helm install teleport teleport/teleport-cluster \
  --create-namespace \
  --namespace teleport \
  -f aws-values.yaml
```

There's also an issue with the first line of shell commands that use [heredocs](https://tldp.org/LDP/abs/html/here-docs.html). In [this section](http://goteleport.com/docs/enterprise/workflow/ssh-approval-pagerduty/?scope=cloud#create-user-and-role-for-access), for example, changing the code snippet at the top of the section from `yaml` to `code` causes it to render like this:

![image](https://user-images.githubusercontent.com/25250668/150868433-89c832e6-7d25-493e-8e64-0a5de9970e06.png)

Using a `yaml` code snippet, though (which the snippet currently uses), it renders on multiple lines as expected:

![image](https://user-images.githubusercontent.com/25250668/150868550-96acb83d-909e-4864-ab4c-ddd199897779.png)

It might be worth noting that [changing this line](https://github.com/gravitational/next/blob/594a81efe6b0fb5674aec854bfa12adfc83aff2c/server/remark-code-snippet.ts#L93) to the following causes the `helm install` command from earlier to render on multiple lines (though probably breaking other stuff):

```ts
      const codeLines = content.split("\\n");
```

**Comment by C-STYR** [comment]
@ptgott thanks for the update.
