### ISSUE TITLE
Switchers

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#82]
## Global ent/oss switcher

Wolfe has not designed it yet, but there will be a global "ent/oss" switcher, probably a toggle near the version that will impact all the content on all pages even between page links. This is for enterprise and oss users not to switch all the time between ent/oss tabs.

Each page will have multiple sections that will be activate based on the global toggle. Ideally titles and some other content will change too. Tab switcher should support global toggle, titles and meta are another component that should change. Some paragraphs should support this too.

## Sticky tab switcher

Wolfe has designed a tab switcher that has a global switcher for config options. See in avocode example with "OS" Linux code switcher (scroll down to see it) 

https://app.avocode.com/revisions/77798465/?design=52101148

This switcher also has to be sticky - multiple config options should "stick" on the same level of content

**Comment by klizhentas** [comment]
@alexwolfe and @iAdramelk take a look at the switchers and typography in prisma docs:

https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-typescript-postgres/

These look great, especially inline code, tabs are also not taking too much space + there are dynamic switchers for various install methods. What can we learn from those and apply in this iteration?

**Comment by klizhentas** [comment]
<img width="699" alt="Screen Shot 2021-03-25 at 8 46 14 AM" src="https://user-images.githubusercontent.com/13717/112501625-a2978c00-8d46-11eb-8f90-97c485ef0580.png">

@alexwolfe see the switchers above, they are page specific and support more options. Our switcher in avocode is a toggle, how would a selector look like?

**Comment by alexwolfe** [comment]
So in the original design I specifically don't want to hide enterprise features. In fact they are just labeled enterprise and its important for them to be visible to devs so they are aware of the features that come with enterprise also, it allows our enterprise users (who are paying us) to find what they need quickly without have to be a second class citizen and click a drop down in order to find relevant information. We should discuss in more detail, probably worth a convo. I imagine you have some use cases that make sense for this so lets sync when you get a chance and tease out an optimal solution.

**Comment by klizhentas** [comment]
<img width="237" alt="Screen Shot 2021-05-31 at 12 00 41 PM" src="https://user-images.githubusercontent.com/13717/120232192-e657b780-c207-11eb-8229-74925d0316b9.png">

@alexwolfe because we have 3 versions: Open Source, Enteprise and Cloud, we need a different switcher, perhaps like the one above?

**Comment by alexwolfe** [comment]
@iAdramelk Ok, here are the designs for the new switch component. I'll do my best to explain how they work. 
The first switcher has 3 options
- Open Source
- Cloud
- Enterprise

The content on the page should change depending on which option you have selected. Some of the content on each page will be shared. Sasha can provide more details. 

The Second Switch is the version selection similar to what we have now. The Difference is that the dropdown will now have separators for each major version (see image below) and a link to "View Additional Versions" that will take user to the github page with a list of all releases. 

![image](https://user-images.githubusercontent.com/407237/120524513-fbf5ea00-c38b-11eb-8dea-2568e8bc4ace.png)
![image](https://user-images.githubusercontent.com/407237/120524525-01533480-c38c-11eb-8f1f-6d6a97694ff9.png)
