### ISSUE TITLE
Multiline code blocks breaks if there is a comment after `\`

### ISSUE THREAD

**Issue by iAdramelk** [gravitational/next#830]
Last line should be a part of the command, but is not because of the comment:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/451207/151201523-8e53b11d-0a78-405c-b8ed-8d483dbc49e3.png">

**Comment by Alqanar** [comment]
This multiline command is incorrect.
The comment must be moved either before or after the multiline command.

i.e.
```
$ sudo teleport start \
--roles=app \
--token=${TOKEN?} \
--auth-server=teleport.example.com:3080 \
--app-name=example-app  \ 
--app-uri=http://localhost:8080
# Change "example-app" to the name of your application.
# Change "http://localhost:8080" to the address of your application.
```
