### ISSUE TITLE
Provide mdx alternatives to custom components

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#86]
## Description

Let's add alternative format for:

* Notes using `<note>` react component
* Proper include tag instead of custom template `{{!...!}}`
* Table component (I personally find it really hard to write tables in markdown)
* Any other custom components we use in markdown?

Send a PR to replace all old legacy components switching to the new engine's ones.
Remove code for unused components

**Comment by iAdramelk** [comment]
Done except `{!...!}` but I think to leave it as is for now.
