### ISSUE TITLE
`scope` and `scopeOnly` for Admonitions

### ISSUE THREAD

**Issue by ptgott** [gravitational/next#867]
Our `Details` component includes a `scopeOnly` property that enables page authors to show the component only for certain scopes, e.g., for Cloud or Enterprise users. It would be great to add the `scopeOnly` and `scope` logic to the `Admonition` component so we could, for example, add warnings directed only to Cloud users.

**Comment by Alqanar** [comment]
Created a task https://app.asana.com/0/1201950389251748/1202072765206279
