### ISSUE TITLE
Use semantic tags to indicate navigation

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/next#87]
We can improve our HTML by adding more semantic tags to the content. This will help crawlers with indexing of our content.

![image](https://user-images.githubusercontent.com/7816406/106533658-99b1d900-64c0-11eb-8af4-6f64868f05c5.png)

1. Use `nav` tags to indicate navigation containers: top, left nav, content nav.
2. Take a look at old Teleport docs and try to use similar tags.

**Comment by iAdramelk** [comment]
Added `<nav>` tags. Decided not to change items themselves to ul/li, because it will increase amount of css, and not necessary help with search engines.
