### ISSUE TITLE
Table of Contents does not scroll fully

### ISSUE THREAD

**Issue by pschisa** [gravitational/next#88]
When a long list of options is present in the table of contents (such as on the https://goteleport.com/teleport/docs/cli-docs/), only a subset of the Table of contents renders and scrolls (I get to "tctl tokens ls") from the top of the page

I then have to scroll all the way down to the bottom of the view the remaining options in the table of contents.

My expectation would be for the full table of contents to load and scroll from the top of the page (otherwise whats the point of having the quick summary)

Im running Chrome and other engineers verified similar behavior on their machines with the table of contents.

**Comment by klizhentas** [comment]
It's a problem with this page that we'd have to fix. We should split this page in 3 different pages and reduce the TOC this way. The TOC has to be brief enough to fit on one page.
