### ISSUE TITLE
Newlines in Markdown are not rendered as spaces

### ISSUE THREAD

**Issue by webvictim** [gravitational/next#91]
Newlines in Markdown are not rendered as spaces, leading to formatting issues like this:

```markdown
## High Availability

!!! tip "Tip"

    Before continuing, please make sure to take a look at the [Cluster State section](architecture/nodes.md#cluster-state)
    in the Teleport Architecture documentation.
```

Output:

![2021-02-03-130132__912x143__maim](https://user-images.githubusercontent.com/897821/106782040-1c04df00-6620-11eb-8239-a044b874a0c6.png)

With the old `mkdocs` engine I believe newlines were converted to spaces which avoided these issues. We have a lot of situations in the docs where newlines are used in lieu of spaces to keep line width relatively consistent, so it's probably easier to fix the engine rather than change all instances in the docs.

**Comment by iAdramelk** [comment]
Should be resolved in #106
