### ISSUE TITLE
Can't change scope in versions

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/next#953]
Once you've set the version you can't change scopes. 

![image](https://user-images.githubusercontent.com/60704961/156882263-738c5250-4d94-4f08-9989-b32a999f0685.png)

Change the scope.  The versions are grayed out and not changeable. 

![image](https://user-images.githubusercontent.com/60704961/156882281-9cca862b-74cc-43c9-bd8b-9feae4e781ab.png)

**Comment by Alqanar** [comment]
This field is expected to disable when cloud scope is selected. This was done due to the fact that the cloud version is always current.

PR on which this was added https://github.com/gravitational/next/pull/353 
Issue https://github.com/gravitational/next/issues/82

**Comment by stevenGravy** [comment]
Thanks @Alqanar .  The problem is how do we test when we're editing different versions and confirming.  Is there a way to disable this when you're editing?

**Comment by Alqanar** [comment]
There is a file `config.ts` in the root. It sets which version is the latest stable version. To change the latest stable version, remove the `latest: true` field from the object and add it to the version you want to test.

**Comment by stevenGravy** [comment]
Thanks, will close this and may submit a README fyi on this to switch the version.
