### ISSUE TITLE
Doc side navigation expanding bug

### ISSUE THREAD

**Issue by kimlisa** [gravitational/next#965]
Links with hashes does not make our left navigation expand ie: https://goteleport.com/docs/setup/reference/cli/#tctl
(this was a result of using the search bar and clicking on a result)

Versus without hash correctly expands navigation ie: https://goteleport.com/docs/setup/reference/cli/

I get kinda lost when the side navigation does not expand, b/c normally I want to browse other subset of the stuff i searched

using chrome on linux

**Comment by C-STYR** [comment]
@Alqanar can this issue be closed?

**Comment by Alqanar** [comment]
@C-STYR  I'm not sure :) if it is enough that the issue is implemented in the gravitational/docs repository, then of course we can close it.

**Comment by C-STYR** [comment]
@Alqanar please duplicate here then - not sure when we are going to cut docs over.  Thanks.
