### ISSUE TITLE
Docs do not deploy new content

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#99]
This content never showed up:

https://github.com/gravitational/teleport/commit/24bc6a18c31f6a713130807cf0b4d3d56eabad1b

**Comment by iAdramelk** [comment]
@klizhentas I disabled submodule update on build for the time of the migration to no mess the branches, and forgot to enable it back, give me a sec.

**Comment by iAdramelk** [comment]
@klizhentas https://goteleport.com/teleport/docs/installation/ works now.
