### ISSUE TITLE
[Development Request] Hide invisible H2 sections in the docs from the table of contents

### ISSUE THREAD

**Issue by ptgott** [gravitational/next#997]
Please fill out the information below: 

### What is the goal of the ticket? 

On a docs page, it is possible to hide an H2 section based on scope using, for example, a `Details` or `ScopedBlock` component. However, these H2 section headings remain in the table of contents on the right side of the screen. Sometimes, pages have H2 sections that are irrelevant to users of a particular scope, so it would be great to hide these sections without a reader wondering why they can click on a TOC link to a section that does not exist.

Currently, our docs page layout renders headings in the TOC using a `tableOfConents` variable that we [populate](https://github.com/gravitational/next/blob/5fc55e156d608182f18b5bf8d4d5e5461d0d9071/server/rehype-headers.ts#L47) via running a `rehype` plugin. However, since `mdx-js` runs `rehype` plugins before rendering JSX, the headers that are passed to `tableOfConents` are not aware of scoped visibility settings. 

Is there a way to query the currently visible headings from, for example, the `AnchorNavigation` component when JSX components are rendered?

Thanks!

**Comment by Alqanar** [comment]
Created a task https://app.asana.com/0/1201950389251748/1202072765206274
